name: CI

on:
  pull_request:
  push:
    branches: [ master, main, embedded-feature ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: |
          npm run lint || echo "Lint warnings/errors ignored for CI pass"

      - name: Build
        run: npm run build
